# Generated by Django 5.0.6 on 2024-07-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_tasks', to='webapp.task')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_types', to='webapp.type')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='webapp.TaskType', to='webapp.type', verbose_name='Типы'),
        ),
    ]
