# Generated by Django 5.0.6 on 2024-07-29 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_task_user_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.task'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.type'),
        ),
    ]
